# Generated by Django 3.2 on 2021-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('nao_concluido', 'Não Concluído')], default='nao_concluido', max_length=15, verbose_name='Status')),
            ],
        ),
    ]
