# Generated by Django 3.2 on 2021-04-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='conteudo',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
